version: 2

sources:
  - name: restaurants
    database: DB_DBT_NHURTEVENT_DEV
    schema: source
    tables:
      - name: restaurants
        identifier: restaurants
  - name: orders
    database: DB_DBT_NHURTEVENT_DEV
    schema: source
    tables:
      - name: orders